### ISSUE TITLE
proxyStore promise not resolving for new tab override on initial launch 

### ISSUE THREAD

**Issue by collectedmind** [tshaddix/webext-redux#106]
I have noticed an issue when creating a chrome_url_override - new tab.  I have to wrap everything in a timeout on the new tab side of things otherwise I get no render on initial launch of chrome. Every subsequent new tab open works fine, even without the timeout.  Timeouts are super brittle and hacky as a solution to this so I was wondering if anyone had encountered this and found a better approach.  Would love to remove the timeout.

```
// This timeout is neccessary to make sure the proxystore on this end is created
// after the store gets wrapped. Otherwise the promise does not resolve.
// Only happens on launch of chrome

setTimeout(function() {
    const proxyStore    = new Store({portName: 'XYZ_EXT'})

    proxyStore.ready().then(() => {
        ReactDOM.render(
            <Provider store={proxyStore}>
                <App />
            </Provider>
            , document.getElementById('xyz-extension-anchor')
        )
    })
}, 100)
```

**Comment by vhmth** [comment]
@collectedmind if you have to wrap the whole thing in a `setTimeout`, it seems like that may point to a potential issue of when this code is getting called in general. Could you post the error you're getting? Do you have a small minimal example showcasing the issue? The `.ready` function tells you when the content script has established a good connection with the background process.

**Comment by collectedmind** [comment]
I did some testing and found that with a simple implementation, it does not cause a problem.  I am gonna go through and try and find the breaking point.

**Comment by vhmth** [comment]
Cool keep us posted! Again, if you can provide a minimal example (or just one in general) via a repo, I can clone and test too

**Comment by collectedmind** [comment]
Sorry for the delay on this.  So I made a super simple example here https://github.com/collectedmind/newtab-example 

This is just a bare bones create-react-app modified to work as a new tab extension.  I simulated the wrapStore happening after the proxyStore call with a timeout.  Works fine on all subsequent instances but on launch the delay causes a blank page returned.

So be sure you have chrome opening a new tab on launch in order to observe this.

**Comment by collectedmind** [comment]
My proposed solution: https://github.com/tshaddix/react-chrome-redux/pull/111

I tested this with the example repo and it was effective.  Let me know what you think.

**Comment by vhmth** [comment]
@collectedmind https://www.useloom.com/share/4d7d685f4e11458cb691407c09ba0468

**Comment by vhmth** [comment]
@collectedmind I actually just read through the PR and realize why you put the timeout in there. I set it to 5s and was able to see what you're seeing - moving convo to PR.

**Comment by tshaddix** [comment]
This is now in `webext-redux@2.0.0`

**Comment by collectedmind** [comment]
Awesome!  Thanks @tshaddix
