### ISSUE TITLE
How big is too big for the local store?

### ISSUE THREAD

**Issue by trentduffy** [tshaddix/webext-redux#146]
Hi all! 

We're working on a chrome extension using react-chrome-redux that regularly gets store sizes of like 5 MB. Is this too big? Will we start seeing performance issues?

**Comment by vhmth** [comment]
Is this for local storage the browser API or the size of the state itself? If it's the size of the state, you are serializing/deserializing 5MB of javascript object for each action that updates your store. We haven't approached a store of this size with the Loom Chrome extension, but I feel like that will have an effect on lower-power devices (lower-end Chrome books).
