### ISSUE TITLE
Store Promise Not Resolving On An Ejected Create React App

### ISSUE THREAD

**Issue by webjunkie01** [tshaddix/webext-redux#177]
Hi guys,

I've been trying to make this package to work on an ejected app created with create-react-app but no matter what I do it does not seem to work. Even with the most basic example the store promise never resolves. 

I've created a repo if anyone is interested in taking a look about what could be wrong. I'm really a newbie when it comes to webpack but I think that's what might be causing the problem. 

Repo: [https://github.com/webjunkie01/ejected](url)

**Comment by tshaddix** [comment]
Hey @webjunkie01  - maybe I'm wrong but it looks like you're using two different `portNames`:

[index.js](https://github.com/webjunkie01/ejected/blob/master/src/index.js):

```js

export const store = new Store({
    portName: 'ejected' // communication port name
});
```

[background.js](https://github.com/webjunkie01/ejected/blob/master/src/background.js):
```js
wrapStore(store, {portName: 'NEVERDIE'});
```

**Comment by tshaddix** [comment]
Changing these to the same name should fix this. In the latest version of `webext-redux` (2.0.1) the `portName` property is optional so you can actually remove it completely and do:

```js
// index.js
...
export const store = new Store();

// background.js
...
wrapStore(store)
```
