### ISSUE TITLE
 Cannot read property 'addListener' of undefined  at new Store (Store.js:90)

### ISSUE THREAD

**Issue by EitanElbaz** [tshaddix/webext-redux#195]
In a previous incarnation of this project, back when it was called `react-chrome-redux` I placed the content side of the store directly within the browser's javascript code (not an extension's content script) which worked really well and the other portion of the store (wrap store) within a background script.

This worked extremely well for my company because all of our react components and styling live within a single codebase for our internal system.

When updating to version 2.0.1 of `webext-redux` this stopped working, producing the following error:

```Uncaught TypeError: Cannot read property 'addListener' of undefined at new Store (Store.js:90)```

I was wondering whether @tshaddix could be so kind to either tell me that I'm being stupid and this use case is still supported or whether support for my use case could possibly be brought back.

Many thanks in advance and keep the great work up!

Edit: The version that's happily working away is `v2.0.0-alpha.4`

**Comment by EitanElbaz** [comment]
Closing the issue because we're just going to bite the bullet and make our extension do all of the rendering. Thanks for this awesome project though!

**Comment by tshaddix** [comment]
Sorry I hadn't got to this yet. If you do need some more help, please let me know!
