### ISSUE TITLE
Type definitions conflict with the latest version of redux

### ISSUE THREAD

**Issue by RobertB4** [tshaddix/webext-redux#221]
Redux now has an observable as part of the store.
https://github.com/reduxjs/redux/blob/8aca937f695997e979bf8c0e03dbf22a2bf284dc/index.d.ts#L247

 I "fixed" it by creating a custom .d.ts file, copy pasted the type definition file of webext-redux and added the observable to the store class for now to silence the compiler, though I guess eventually this has to be fixed on the library level.

**Comment by tshaddix** [comment]
@RobertB4 Thanks for reporting. Could you open a pull request and add your changes to this libraries TS definitions? It would be very appreciated!

**Comment by tshaddix** [comment]
Resolved in #236
