### ISSUE TITLE
usage with create-react-app without ejecting

### ISSUE THREAD

**Issue by abhijithvijayan** [tshaddix/webext-redux#222]
Is it possible to use this package with CRA without breaking anything?

I have set up CRA with redux & react-redux like a regular webapp, and CRA's default endpoint will be an `index.js`

Is there any example you can point out to?

**Comment by abhijithvijayan** [comment]
This is my current set up without webext-redux

https://github.com/onepassapp/onepass/

**Comment by abhijithvijayan** [comment]
I use create-react-app with custom config(without ejecting) to provide code sharing from the next.js app

**Comment by VasilyShelkov** [comment]
Hey I'm maintaining a fork of CRA which specifically allows the development of browser extensions https://github.com/VasilyShelkov/create-react-extension

**Comment by bartekus** [comment]
You can also just patch your normal CRA and use `webpack-extension-reloader`.
Here is an example: [cra-modular-redux-auth0-saga-browser-extension](https://github.com/bartekus/cra-modular-redux-auth0-saga-browser-extension) and a quick write-up about [how to do it](https://bartekus.com/cra-browser-extension/).

**Comment by abhijithvijayan** [comment]
Hey, I made my own(quite popular) starter https://github.com/abhijithvijayan/web-extension-starter

**Comment by bartekus** [comment]
That's pretty cool, however I do not want to eject.

**Comment by abhijithvijayan** [comment]
@bartekus This is not a CRA app

**Comment by bartekus** [comment]
@abhijithvijayan I see we're after different things then, my intent is to simply use CRA for building browser extensions. To each their own I guess.

**Comment by abhijithvijayan** [comment]
I wanted that initially just to use React in the front-end.

On trying that out, I found out it was better to set up custom webpack config with autoreloading and browser tailored manifest generation.

You can always try out the starter if you find it is better for webextensions
