### ISSUE TITLE
[Question] How can I use it with applyMiddleware, createStore

### ISSUE THREAD

**Issue by arthur791004** [tshaddix/webext-redux#25]
Hi,

as title, could I combine applyMiddleware, createStore with the Store from this module?

Thanks.

**Comment by vhmth** [comment]
@arthur791004 you're talking about the frontend `Store` correct? Just making sure.

**Comment by tshaddix** [comment]
Hi @arthur791004!

I have not tried any UI-side middleware with the ProxyStore. The main issue is that we don't have any `createStore` function at this time, which would handle the middleware implementation. It should be relatively easy to implement and support most basic cases ([it's just wrapping the dispatch](http://redux.js.org/docs/advanced/Middleware.html)). What kind of middleware are you hoping to use on the UI side?

The background/event page is meant to have a plain 'ole Redux store, so you can use as much middleware as you want!

**Comment by arthur791004** [comment]
@vhmth Yes, I am talking about the Store class used in content scripts or popup
@tshaddix OK, I got it and I misunderstand something... Thanks.

**Comment by vhmth** [comment]
@arthur791004 do you have a legitimate use case for using middleware in your content scripts though? If that's the case, we should pursue this. If not, we'll wait until it's something someone wants. :-P (Unless you wanted to just implement it @tshaddix)

**Comment by tshaddix** [comment]
@vhmth I'm stumped at this point.

On one hand, it would be straight forward to implement and may have some great opportunities to enable UI-side middleware.

On the other hand, you'd now have multiple layers of middleware which only run based on certain UI Components. That's definitely branching from the "Redux Ideology" which would have us keep reducer and middleware logic in a single place (event-page).

What are your thoughts?

**Comment by vhmth** [comment]
I see the issue if we go with the raw `createStore` approach, but we could offer a `createStore` method that explicitly doesn't take a reducer and automatically creates a `proxyStore`. We could call it `createProxyStore` or something like that so there isn't confusion when skimming over the code.

**Comment by tshaddix** [comment]
@vhmth Right, I definitely don't think reducers should be offered `ProxyStore` side. My suggestion and your suggestion are in parity. I think your suggestion to name the function something other than `createStore` is a good one.

My point of uncertainty is focused around the hierarchical middleware pattern this would create.

I look forward to hearing from @arthur791004 about use case.

**Comment by vhmth** [comment]
I can imagine someone wanting to have some action logging middleware on the front-end (for dev purposes). I've never personally needed this though, so I'll hold up for @arthur791004 to chime in as well.

**Comment by arthur791004** [comment]
@tshaddix
Sorry for late reply,

I don't have any use case, but I think that logging middleware is a good idea as @vhmth said.

However, if the actions also are proxy actions, I think there is no need to do it XD

Why I mentioned proxy actions is that I encountered the action sent the request to the http api but the current page is https, so I got en error...

Thanks.

**Comment by tshaddix** [comment]
Closing this issue for now :)

**Comment by paulius005** [comment]
Reviving this, found a nice usecase.

Started using Raven to log our error events. 

Applied some simple middleware to store each `action` as a `breadcrumb` leading up to an error being logged.

It would be great if we could wrap our content scripts with some extra middleware. However I do see your point @tshaddix that running multiple layers of middleware would break from the "Redux Ideology". 🤔

**Comment by vhmth** [comment]
Just for clarification for others, Raven is a library by [Sentry](https://sentry.io).

**Comment by tshaddix** [comment]
@paulius005 Ah yes, Raven.

So I'm definitely interested in supporting your use-case. I don't think this package should block you from doing things that good developers do :)

So let's dive into this. What would the middleware contents look like in your example? What would it be storing/doing after each action?

**Comment by paulius005** [comment]
Currently we're only doing read only actions as such:

```
const ravenActionState = Raven => {
  return store => next => action => {
    Raven.captureBreadcrumb({
      message:  action.type,
      category: REDUX_ACTION_STATE,
      data:     store.getState()
    });

    next(action);
  };
};
```

Only thing I see us doing in the future is providing an options argument for a state and actions mutators to modify the data before attaching it to a breadcrumb. However this still leaves the middleware as a read only module from the store perspective.

**Comment by tshaddix** [comment]
@paulius005 I'm still having a bit of trouble wrapping my head around this. Sorry if I'm being a little dense.

Is there a reason you wouldn't do it as a traditional redux middleware in the background/event page?

**Comment by vhmth** [comment]
@tshaddix we have 4 different script contexts errors can arise from:

* popup
* our main recorder content script
* our gmail integration script
* the background script

The errors that arise from these contexts are very different just because we're doing very different work in all 4, so we decided to put Raven in each one. If we wanted errors surfaced in the gmail context to get to Raven in the background, we'd have to write plumbing to ferry those errors cross-context, which seems like a breaking of separation of concerns (since the concern should be errors scoped to different contexts).

**Comment by tshaddix** [comment]
@vhmth Ah, thanks for clarifying. Now I get it. You want to make sure and not miss the global errors or any other major errors on the content scripts. You have Raven running content-script side to catch these.

Cool. So yea, let's explore options for this. One option is adding some middleware layer to the proxy store. 

In the meantime, you might save yourself some headache by using a generator function:

```
import store from './store'

export function wrapAction (fn) {
  return function () {
    const action = fn.apply(this, [...arguments]);
    Raven.captureBreadcrumb({
      message:  action.type,
      category: REDUX_ACTION_STATE,
      data:     store.getState()
    });
    return action;
  };
}

// usage

const myAction = wrapAction((id, name) => {
  return {type: ..., payload: ...};
});

myAction(1, 'Tyler');
```

**Comment by tshaddix** [comment]
@paulius005 If you want to put together a proposal or PR, I'd love to review :)

**Comment by paulius005** [comment]
@tshaddix just saw this. Will do, should have some time this evening

**Comment by EdmundLeex** [comment]
question, how do you deal with things that should run in the background? say api calls. Putting the middleware in content script / popup is not guarantee to work because user might dismiss the page before the async action completes...

**Comment by vhmth** [comment]
@EdmundLeex check out this part of the README:

https://github.com/tshaddix/react-chrome-redux#3-optional-implement-actions-whose-logic-only-happens-in-the-background-script-we-call-them-aliases

**Comment by EdmundLeex** [comment]
@vhmth aha. thanks a lot. scratched my head for quite a while...

**Comment by vhmth** [comment]
@EdmundLeex sure thing - I'm going to delete your comments just to keep this specific issue clean.

**Comment by tshaddix** [comment]
We now support middleware in proxy stores in `webext-redux@2.0.0` :)
