### ISSUE TITLE
store crashes if a webpage has an id="global" element on it

### ISSUE THREAD

**Issue by mavalos1** [tshaddix/webext-redux#251]
If a page has an element that has id="global" like this:
<div id="global">A div with Id global</div>

it will result in util.js breaking the store at checking for global.chrome and/or browser.
![image-2020-05-25-08-31-42-553](https://user-images.githubusercontent.com/44337809/84885383-2e480200-b0bd-11ea-8c88-d2f85560d40c.png)

**Comment by tshaddix** [comment]
Interesting. It seems like we could just swap `global` for `window` to fix this. Thanks for submitting a ticket.
