### ISSUE TITLE
Doesn't work with react-redux v8

### ISSUE THREAD

**Issue by spinbag** [tshaddix/webext-redux#280]
Trying to use this library with `react-redux` v8.0.1 breaks the app. Though it works with `react-redux` v7.2.8. 

Steps to reproduce:
1. Initialise a store in the background script
2. Initialise a proxy store in the UI
3. Try to get state using `useSelector`

Result:
![Screenshot 2022-04-29 at 15 18 39](https://user-images.githubusercontent.com/9194892/165943340-8d3be452-cec8-444d-93a2-ea5a3bd03b59.png)

**Comment by buryo** [comment]
Same error
<img width="913" alt="image" src="https://user-images.githubusercontent.com/21952570/167632230-b909682e-8816-451e-a119-8b846db02804.png">

Using `react-redux` 8.0

**Comment by buryo** [comment]
Can confirm this. Getting the same error using `react-redux` v8.0

**Comment by eduardoacskimlinks** [comment]
> Trying to use this library with `react-redux` v8.0.1 breaks the app. Though it works with `react-redux` v7.2.8.
> 
> Steps to reproduce:
> 
> 1. Initialise a store in the background script
> 2. Initialise a proxy store in the UI
> 3. Try to get state using `useSelector`
> 
> Result: ![Screenshot 2022-04-29 at 15 18 39](https://user-images.githubusercontent.com/9194892/165943340-8d3be452-cec8-444d-93a2-ea5a3bd03b59.png)

Keep in mind that currently, the library has a hardcode limitation regarding the `Redux` version, which it's likely to be causing the problem https://github.com/tshaddix/webext-redux/blob/master/package.json#L52

**Comment by llGaetanll** [comment]
A solution (although not ideal) is to downgrade to `react-redux@7` for the time being. This fixed the issue for me
```
npm i react-redux@7
```
