### ISSUE TITLE
How to re-sync store from "content script" with background.js (service worker)?

### ISSUE THREAD

**Issue by lukasfarina** [tshaddix/webext-redux#295]
Hey friends, I have a chrome extension and I am suffering from IDLE after being inactive for 30 seconds. After that, when trying to perform a dispatch, my content_script does not respond, as it is no longer connected to the store.

**Comment by vladnikolov86** [comment]
Do something like that 
 chrome.runtime.sendMessage({
        type: "Random Message",
      });
  in an interval, like every 10 seconds. This will keep your extension and its state alive.

**Comment by lukasfarina** [comment]
> Do something like that chrome.runtime.sendMessage({ type: "Random Message", }); in an interval, like every 10 seconds. This will keep your extension and its state alive.

I did, but it seems that this still didn't solve or increase the Aba cache much.

What I did to solve it was: When activating the serviceWorker (background.js), I send a manual message to the content script and reassemble the components and the store using new Store(); This resolved it here, thank you very much for your help!
