### ISSUE TITLE
Unable to use Redux Devtools in background page?

### ISSUE THREAD

**Issue by lvelazquez** [tshaddix/webext-redux#78]
Thank you for this package!  Apologies if this is a dumb question (not so sure where to ask) but does the redux devtools extension work with this? I see the tab in inspection but getting "No store found" in the redux tab for all pages and see that window.__REDUX_DEVTOOLS_EXTENSION__ is undefined as well in the source. I've noticed none of the  #react-chrome-redux-examples have devtools implementation but I tried adding it to the clicker with no luck and can't find anything in the documentation. Would love some help!

**Comment by tshaddix** [comment]
@lvelazquez Hey there!

Hmmm... I remember someone asking this before and I believe the conclusion was "It does not work". I have not tried this myself...

@vhmth @paulius005 thoughts?

**Comment by vhmth** [comment]
I'm not quite sure how Redux Devtools picks up on stores in the first place (that's probably the best place to start). Seems like it's pretty straightforward:

https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md

@lvelazquez do you have a repo showing what you've tried? I can try building off that.

**Comment by lvelazquez** [comment]
Hi @vhmth @tshaddix I do not have this in a repo currently, I tried it locally on a project but just to keep it simple used the clicker example from react-chrome-redux-examples to see if the store  would come up, it partially worked on the popup but not in the background page where the store is and I'd find it more useful

**Comment by vhmth** [comment]
@lvelazquez sorry for the slow replies here! Just getting out of a rut of being out-of-sync with my email.

Could you either:

1. Paste here the code you're using to get Redux Devtools to pick up on the background store?
2. Zip the code and then upload somewhere and link?

It would be helpful to get your code for 2 reasons:

1. Help you diagnose the issue.
2. As historical context for ourselves and others who may run into the same issue.

Gracias! :-)

**Comment by m0a** [comment]
I use [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools)

```js:background.js
import { wrapStore, alias } from 'react-chrome-redux';
import { composeWithDevTools } from 'remote-redux-devtools';
import thunkMiddleware from 'redux-thunk';
import { createStore, applyMiddleware, compose } from 'redux';
import reducer from './sidebar/reducers';
import App from './sidebar/index';
import aliases from './sidebar/actions/aliases';


const store = createStore(reducer, composeWithDevTools(
  applyMiddleware(alias(aliases), thunkMiddleware)
  // other store enhancers if any
));

wrapStore(store, { portName: 'MY_APP' });
```

It works

**Comment by rcornacchia** [comment]
Remote-redux-devtools worked for me as well.
I wasn't able to render a Devtools container to the page directly, but the remote-redux-devtools chrome extension was able to display one in a popup window.

Maybe it's a timing issue?

**Comment by vhmth** [comment]
@rcornacchia that sounds painful (to have the devtools display in a popup window). Have you tried looking at the background page directly and rendering something there? You can get to your background page like this:

`chrome-extension://<extension_id>/path/to/background.html`

If you haven't specifically set an HTML file to your background page, then the path is on root and it's just `background.html`.

**Comment by vhmth** [comment]
@m0a are you rendering the devtools UI in the background page itself? How are you seeing that surface?

**Comment by m0a** [comment]
rendering UI in the contentescripts.
try to run devtool from http://remotedev.io/local/
it work

**Comment by malyzeli** [comment]
@m0a And how do you connect with Redux DevTools? Tried to put the same code into my `background.js` with no results. Thanks for help!

**Comment by vhmth** [comment]
Hey people - if you're running into this issue, mind making a short video showing what you're seeing? It might be useful to see if you can breakpoint and showcase that you're not seeing what you normally should. Another option is to share a repo of code that showcases the issue.

**Comment by qbraet** [comment]
For me it only worked with a local server

`
import { composeWithDevTools } from 'remote-redux-devtools';

...

const composeEnhancers = composeWithDevTools({ realtime: true, hostname: 'localhost', port: 8000 });

const sagaMiddleware = createSagaMiddleware();
const store = createStore(rootReducer, composeEnhancers(
  applyMiddleware(promise, sagaMiddleware))
);
`

And install/run devserver:
https://github.com/zalmoxisus/remotedev-server (just adding the script and running it in a terminal is ok)

don't forget to go to the settings of your remote devtools window and select the local server.

**Comment by SudoPlz** [comment]
@qbraet 's suggestion worked for me.

**Comment by dbuezas** [comment]
https://github.com/zalmoxisus/remotedev-server isn't working for me (something about a compilation error)

use https://github.com/tranquan/remotedev-server instead and everything works in @qbaret answer

**Comment by dbuezas** [comment]
Oh this remotedev stuff is not even needed.
just need to add 
```
<script src="chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/redux-devtools-extension.js" />
```
to background.html
and use remote-redux-devtools as @m0a says

**Comment by johnnyfekete** [comment]
If anyone wants to use it with **@reduxjs/toolkit**, here's how I could make it work:

Install [@redux-devtools/remote](https://www.npmjs.com/package/@redux-devtools/remote)

```js
import { devToolsEnhancer } from '@redux-devtools/remote';

const store = configureStore({
  reducers,
  // ... rest of configuration ...
  devTools: false,
  enhancers: [
    devToolsEnhancer({ realtime: true, hostname: 'localhost', port: 8000 }),
  ],
});
```

But it's not enough 🙂

Install [@redux-devtools/cli](https://www.npmjs.com/package/@redux-devtools/cli) as it's explained in the package, and start it.

The hostname and port should match with the `devToolsEnhancer`.

It's a tool that needs to be running during development, so make sure to start it.

Finally, start a redux dev tool instance, I used [redux-devtools-app](https://www.npmjs.com/package/redux-devtools-app) but it can be the one from the browser.

Now, click on Settings, and make sure you're connecting to the right host + port.

<img width="888" alt="Screenshot 2022-09-25 at 21 00 05" src="https://user-images.githubusercontent.com/908033/192160705-82e991b8-3f6d-4212-b6fa-b09ea72c13c8.png">

You should see everything loaded. 🎉
