### ISSUE TITLE
Making Aliases More Understandable

### ISSUE THREAD

**Issue by vhmth** [tshaddix/webext-redux#94]
Teeing off our email, we should put some thought into how we can clear up confusion on what an alias is. Honestly, after looking at this repo, an `examples` folder would probably be a good idea. One can be named `aliases` to showcase how they work. This won't necessarily cut down on the number of questions about them, but then we have an example to point people to.

I'll be keeping a list of improvements we can make to the doc here as we discuss:

* `examples` folder with one showcasing aliases and what they do

**Comment by tshaddix** [comment]
@vhmth I think you're right. Examples folder would be a great reference point. We can probably throw the [extraneous examples repo](https://github.com/tshaddix/react-chrome-redux-examples) in there as a started and then add some more specific examples (such as aliases).

I can start by throwing in the "basic" example in a new branch.

**Comment by vhmth** [comment]
That would be awesome @tshaddix!

**Comment by vhmth** [comment]
@tshaddix recently @paulius005 stumbled upon electron-redux, and they supply a util called `createAliasedAction`. Maybe we introduce a helper that does something in the same manner? This could keep all the actions in the same place and you basically just choose where the creator/action gets called by using this util!

**Comment by lmenus** [comment]
+1, examples badly needed! 😢

**Comment by vhmth** [comment]
Hey y'all - lmk what you think of this?

https://www.useloom.com/share/d3e482bbc3354bd0b1c1b6fadb5f8fd6

**Comment by tshaddix** [comment]
Let's combine this in #141
